language: python
python: 3.6
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
 - TOXENV=py34
 - TOXENV=py35
 - TOXENV=py36

install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
